---
- name: install apache webserver
  apt:
    pkg: "{{ packages }}"
    state: present
    force: yes
    cache_valid_time: 3600
  vars:
    packages:
    - apache2
    - apache2-doc
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
