---
- name: install curl and unzip
  apt:
    pkg: "{{ packages }}"
    state: present
    force: yes
    cache_valid_time: 3600
  vars:
    packages:
      - unzip
      - curl
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: download kibana
  get_url:
    url: http://download.elasticsearch.org/kibana/kibana/kibana-{{ kibana_version }}.tar.gz
    dest: /tmp/kibana.tar.gz
    mode: 0755
    owner: vagrant

- name: create www group
  group:
    name: www
    state: present

- name: ensure vagrant user exists and is added to www group
  user:
    name: vagrant
    shell: /bin/bash
    groups: www
    append: yes

- name: create www directory for kibana
  file:
    path: /var/www/
    owner: vagrant
    group: www
    mode: 04755
    recurse: yes

- name: unarchive kibana
  become: yes
  become_user: vagrant
  unarchive:
    src: /tmp/kibana.tar.gz
    dest: /tmp/

- name: put kibana in place
  shell: cp -r /tmp/kibana-{{ kibana_version }}/* /var/www/html/
  notify: restart httpd

- name: install default dashboard
  copy:
    src: default.json
    dest: /var/www/html/app/dashboards/default.json
    group: www
    owner: vagrant
